spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/benghuai2.0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
---

#spring:
#  mvc:
#    static-path-pattern: /static/*

debug: true